[package]
authors = ["ModBox21"]
description = "ModBox21 native Bethesda archive library with PyO3 bindings"
edition = "2024"

include = [
  "src/**",
  "Cargo.toml"
]

name = "bsarchive_native"
version = "1.0.0"

[lib]
name = "bsarchive_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "2.11.1"
bstr = "1.12.1"
directxtex = { workspace = true }
flate2 = { version = "1.1.9", default-features = false, features = ["any_zlib"] }
lz4_flex = { version = "0.13.0", default-features = false, features = ["std"] }
libdeflater = "1.25.2"
lzzzz = "2.0.0"
memmap2 = "0.9.10"
pyo3 = { workspace = true, features = ["extension-module", "abi3-py310"] }
rayon = "1"
serde_json = { workspace = true }
thiserror = { workspace = true }
walkdir = "2.5.0"

[dev-dependencies]
anyhow = "1.0.102"

[features]
default = ["flate2/zlib-ng"]
