"""Record type alias and display helpers."""
from __future__ import annotations

RECORD_TYPE_SIGNATURE_ALIASES: dict[str, str] = {
    "AcousticSpaces": "ASPC",
    "Actions": "AACT",
    "Activators": "ACTI",
    "ActorValueInformation": "AVIF",
    "AddonNodes": "ADDN",
    "AimModels": "AMDL",
    "AnimatedObjects": "ANIO",
    "AnimationSoundTagSets": "STAG",
    "Ammo": "AMMO",
    "Ammunitions": "AMMO",
    "ArmorAddons": "ARMA",
    "Armors": "ARMO",
    "ArtObjects": "ARTO",
    "AssociationTypes": "ASTP",
    "AttractionRules": "AORU",
    "AudioCategorySnapshots": "SCSN",
    "AudioEffectChains": "AECH",
    "BendableSplines": "BNDS",
    "Bodies": "BPTD",
    "BodyParts": "BPTD",
    "Books": "BOOK",
    "CameraPaths": "CPTH",
    "CameraShots": "CAMS",
    "Classes": "CLAS",
    "Climates": "CLMT",
    "CollisionLayers": "COLL",
    "Colors": "CLFM",
    "CombatStyles": "CSTY",
    "Components": "CMPO",
    "ConstructibleObjects": "COBJ",
    "Containers": "CONT",
    "Creatures": "NPC_",
    "DamageTypes": "DMGT",
    "Debris": "DEBR",
    "DefaultObjectManagers": "DFOB",
    "DefaultObjects": "DOBJ",
    "DialogViews": "DLVW",
    "Doors": "DOOR",
    "EffectShaders": "EFSH",
    "EncounterZones": "ECZN",
    "EquipTypes": "EQUP",
    "Explosions": "EXPL",
    "Eyes": "EYES",
    "Factions": "FACT",
    "Florae": "FLOR",
    "FootstepSets": "FSTS",
    "Footsteps": "FSTP",
    "FormLists": "FLST",
    "Furniture": "FURN",
    "GameSettings": "GMST",
    "Globals": "GLOB",
    "GodRays": "GDRY",
    "Grasses": "GRAS",
    "Hairs": "HAIR",
    "Hazards": "HAZD",
    "HeadParts": "HDPT",
    "Holotapes": "NOTE",
    "IdleAnimations": "IDLE",
    "IdleMarkers": "IDLM",
    "ImageSpaceAdapters": "IMAD",
    "ImageSpaces": "IMGS",
    "ImpactDataSets": "IPDS",
    "Impacts": "IPCT",
    "Ingestibles": "ALCH",
    "Ingredients": "INGR",
    "InstanceNamingRules": "INNR",
    "Keys": "KEYM",
    "Keywords": "KYWD",
    "LandscapeTextures": "LTEX",
    "Layers": "LAYR",
    "LensFlares": "LENS",
    "LeveledCreatures": "LVLN",
    "LeveledItems": "LVLI",
    "LeveledNpcs": "LVLN",
    "Lights": "LIGH",
    "LightingTemplates": "LGTM",
    "LoadScreens": "LSCR",
    "LocationReferenceTypes": "LCRT",
    "Locations": "LCTN",
    "MagicEffects": "MGEF",
    "MaterialObjects": "MATO",
    "MaterialSwaps": "MSWP",
    "MaterialTypes": "MATT",
    "Messages": "MESG",
    "MiscItems": "MISC",
    "MovableStatics": "MSTT",
    "MoveableStatics": "MSTT",
    "MovementTypes": "MOVT",
    "MusicTracks": "MUST",
    "MusicTypes": "MUSC",
    "NavigationMeshInfoMaps": "NAVI",
    "NavigationMeshObstacleManagers": "NOCM",
    "Notes": "NOTE",
    "Npcs": "NPC_",
    "ObjectEffects": "ENCH",
    "ObjectModifications": "OMOD",
    "ObjectVisibilityManagers": "OVIS",
    "Outfits": "OTFT",
    "Packages": "PACK",
    "PackIns": "PKIN",
    "Perks": "PERK",
    "Projectiles": "PROJ",
    "Quests": "QUST",
    "Races": "RACE",
    "ReferenceGroups": "RFGP",
    "Regions": "REGN",
    "Relationships": "RELA",
    "ReverbParameters": "REVB",
    "SceneCollections": "SCCO",
    "ShaderParticleGeometries": "SPGD",
    "SoundCategories": "SNCT",
    "SoundDescriptors": "SNDR",
    "SoundKeywordMappings": "KSSM",
    "SoundMarkers": "SNDR",
    "SoundOutputModels": "SOPM",
    "Sounds": "SOUN",
    "Spells": "SPEL",
    "StaticCollections": "SCOL",
    "Statics": "STAT",
    "StoryManagerBranchNodes": "SMBN",
    "StoryManagerEventNodes": "SMEN",
    "StoryManagerQuestNodes": "SMQN",
    "TalkingActivators": "TACT",
    "Terminals": "TERM",
    "TextureSets": "TXST",
    "Transforms": "TRNS",
    "Trees": "TREE",
    "VisualEffects": "RFCT",
    "VoiceTypes": "VTYP",
    "Waters": "WATR",
    "Weather": "WTHR",
    "Weapons": "WEAP",
    "Worldspaces": "WRLD",
    "Zooms": "ZOOM",
}


def record_type_signature(record_type: str) -> str:
    if not record_type:
        return record_type
    alias = RECORD_TYPE_SIGNATURE_ALIASES.get(record_type)
    if alias is not None:
        return alias
    return record_type


def record_type_display_label(record_type: str, game: str | None = None) -> str:
    signature = record_type_signature(record_type)
    if game:
        try:
            from creation_lib.esp.schema import get_schema

            spec = get_schema(game).records.get(signature.upper())
        except Exception:
            spec = None
        if spec is not None and spec.display_label:
            return spec.display_label
    return record_type if signature == record_type else signature


__all__ = [
    "RECORD_TYPE_SIGNATURE_ALIASES",
    "record_type_display_label",
    "record_type_signature",
]
